backend:
  name: github
  repo: JohnLinLife/JohnLinLife.github.io
  branch: main
  auth_scope: repo
  squash_merges: true

media_folder: "source/images"
public_folder: "/images"

site_url: "https://johnlinlife.github.io"
display_url: "https://johnlinlife.github.io"
logo_url: "https://johnlinlife.github.io/img/avatar.jpg"

editor:
  preview: true

collections:
  - name: "posts"
    label: "文章"
    label_singular: "文章"
    folder: "source/_posts"
    create: true
    delete: true
    extension: "md"
    format: "frontmatter"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "{{year}}/{{month}}/{{day}}/{{slug}}/"
    fields:
      - { label: "标题", name: "title", widget: "string", required: true }
      - { label: "发布日期", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss", required: true }
      - { label: "标签", name: "tags", widget: "list", required: false, default: [] }
      - { label: "分类", name: "categories", widget: "list", required: false, default: [] }
      - { label: "置顶", name: "top", widget: "boolean", required: false, default: false }
      - { label: "摘要", name: "excerpt", widget: "text", required: false }
      - { label: "封面图", name: "cover", widget: "image", required: false }
      - { label: "文章内容", name: "body", widget: "markdown", required: true }
    default:
      layout: "post"
      date: "{{now}}"
      tags: []
      categories: []